version: '3.1'

services:
  bot:
    image: jp0id/teletweet:v2
    restart: always
    volumes:
      - ./env/auth.json:/TeleTweet/teletweet/auth.json
    env_file:
      - env/teletweet.env

  web:
    image: jp0id/teletweet:v2
    restart: always
    env_file:
      - env/teletweet.env
    working_dir: /TeleTweet/twauth-web
    command: python twauth.py -h=0.0.0.0
    ports:
      - "8888:8888"
